"""Braids approximating single-qubit gates on three Fibonacci anyons.

Generated by compile_gates.py; see there for the conventions. Each word is
a list of (generator, exponent) read as the matrix product s_g1^k1 s_g2^k2 ...,
so the last entry is performed first. Generator 1 exchanges anyons 1 and 2,
generator 2 anyons 2 and 3; positive exponents are counterclockwise.
The error is sqrt(1 - |tr(G^dag U)| / 2), ignoring the global phase.
"""

GATES = {
    "X": ([(2, -2), (1, 4), (2, -2), (1, 4), (2, -2), (1, 4), (2, -2)], 2.196e-03),
    "Y": ([(1, -4), (2, -2), (1, 4), (2, -2), (1, 4), (2, -2), (1, 4), (2, -2), (1, 1)], 2.196e-03),
    "Z": ([(1, 5)], 0.000e+00),
    "H": ([(1, -1), (2, 4), (1, 3), (2, 4), (1, -4), (2, -4), (1, 3), (2, -4), (1, -2), (2, 1)], 4.820e-03),
    "S": ([(1, -2), (2, -4), (1, 4), (2, 3), (1, 3), (2, -3), (1, -4), (2, 5), (1, 2), (2, -2)], 3.377e-03),
    "T": ([(2, -2), (1, 4), (2, -2), (1, 2), (2, 4), (1, -2), (2, -3), (1, 4), (2, -2)], 2.863e-03),
}
